INSERT INTO
recipes(title, description, directions, prep_minutes, servings, image_link, difficulty, cuisine, dietary_restriction, creator_id)
VALUES
  ('Creamy Chipotle Tomato Soup',
  'If youre a fellow spicy food lover and also into tomato soup, yore going to love this chipotle tomato soup! Its inspired by a similar dish from a restaurant called Eloisa in Santa Fe. While the restaurant (sadly) had to close, we couldnt shake the memory of this delicious soup! So we got into the kitchen, did some tinkering, and knew we had to share! This creamy, spicy, smoky soup is plant-based, gluten-free, and the perfect companion for sandwiches and salads! Just 10 ingredients and 1 pot required. Lets get spicy!',
  'In a large pot or Dutch oven, heat olive oil over medium-low heat. Add onion and cook, stirring occasionally, until softened and translucent — about 3 minutes. Add the celery and carrots, and stir to combine. Turn the heat to medium and sauté for 4-5 minutes, or until the veggies are fragrant and brightened in color. Add the garlic, salt, oregano, chipotle pepper(s), and adobo sauce. Mix well, and smash the chipotle pepper with a wooden spoon to break it up slightly. Cook for 2 minutes more. Add the fire-roasted tomatoes and the water, and stir. Bring to a boil, then reduce to a simmer and cover, cooking for 10 minutes, or until the carrots are very tender. Turn off the heat and use an immersion blender to purée the soup (or if using a regular blender, let the soup cool for at least 10 minutes first to avoid an explosion). Using a high-speed blender will give you a smoother soup! But we dont mind the slight texture the immersion blender leaves behind. Once the soup is blended, add the coconut milk and return the soup to a slight simmer, just to heat it through. Enjoy warm! Its delicious served with grilled "cheese" sandwiches, vegan "tuna" melts, or garlic bread. Optionally, garnish with swirls of coconut milk and adobo sauce (if you like it extra spicy!) and Chili Lime Roasted Pepitas. Leftover soup will keep in a sealed container in the refrigerator for 3-4 days or in the freezer for up to 1 month. Reheat on the stovetop or in the microwave until warmed through.',
  45,
  6,
  'https://minimalistbaker.com/wp-content/uploads/2021/11/Creamy-Chipotle-Tomato-Soup-10-ingredients-1-pot-SPICY-plant-based-gluten-free-minimalistbaker-recipe-plantbased-chipotle-tomato-7.jpg',
  'easy',
  'spanish',
  'vegan',
  1),

  ('Bobs Famous Wings',
  'I love the flavor and ease of cooking chicken wings on the grill. They are truly no fuss, no muss and finger lickin good! Classic Buffalo chicken wings are fried but I love the flavor and ease of cooking them on the grill. They are truly no fuss, no muss and finger-lickin’ good! The key is to cook them over a moderate flame so that the fat renders out and the skin gets nice and crispy.',
  'Heat the grill to medium-high. Season the wings with salt and pepper. Using grill tongs, dip a wad of paper towels in oil, then carefully rub the grill grate until glossy and coated. Grill the wings, covered, flipping occasionally, until they are golden brown, crispy and completely cooked through, about 20 minutes. Keep a close eye on the grill: if there are flare-ups or the wings begin to burn, move the wings to a cooler part of the grill or reduce the heat. You dont want grill marks on the wings; just a nice and even golden-brown color.',
  30,
  4,
  'https://images.pexels.com/photos/7169619/pexels-photo-7169619.jpeg',
  'easy',
  'american',
  'keto',
  1),

  ('Simple Ramen',
  'Easy homemade chicken ramen, with a flavorful broth, roasted chicken, fresh veggies, lots of noodles, and a soft cooked egg. Inspired by traditional Japanese ramen, but on the table in under an hour. Real Japanese ramen, the kind that my Honey tells stories about, takes years and great skill to perfect. I wanted to create a simple ramen noodle soup that reminded him of Japan, but could be made quickly, with ingredients on hand.',
  'Cook the chicken*: Preheat the oven to 375℉. Season the chicken generously with salt and pepper. Melt the butter in a large oven-safe skillet over medium heat. Add the chicken, skin-side down, and cook until the skin is golden brown and releases easily from the pan, about 5-7 minutes. Flip the chicken over and cook for another 4-5 minutes, until golden. Transfer the skillet to the oven and roast for 15-20 minutes, until the chicken is cooked through. Remove from the oven, transfer the chicken to a plate and cover with foil until ready to serve.',
  60,
  2,
  'https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg',
  'moderate',
  'japanese',
  'lactose-free',
  21),

  ('Moms Spaghetti',
  'Easy weeknight friendly spaghetti and meat sauce thats made completely from scratch. Use ground beef, turkey, pork, chicken or lamb to make this simple spaghetti recipe. For this spaghetti, we turn to our favorite quick meat sauce recipe. Its made using one-pot, is ultra flavorful, and can be made in under 45 minutes. The spaghetti sauce is also perfect for making ahead. It can be refrigerated for up to three days and stored in your freezer for about three months.',
  'Heat the oil in a large pot over medium-high heat (we use a Dutch oven). Add the meat and cook until browned, about 8 minutes. As the meat cooks, use a wooden spoon to break it up into smaller crumbles. Add the onions and cook, stirring every once and a while, until softened, about 5 minutes. Stir in the garlic, tomato paste, oregano, and red pepper flakes and cook, stirring continuously for about 1 minute. Pour in the water and use a wooden spoon to scrape up any bits of meat or onion stuck to the bottom of the pot. Stir in the tomatoes, 3/4 teaspoon of salt, and a generous pinch of black pepper. Bring the sauce to a low simmer. Cook, uncovered, at a low simmer for 25 minutes. As it cooks, stir and taste the sauce a few times so you can adjust the seasoning accordingly (see notes for suggestions).',
  45,
  6,
  'https://images.pexels.com/photos/4057700/pexels-photo-4057700.jpeg',
  'easy',
  'italian',
  null,
  20),

  ('Korean Hot Pot',
  'As with a typical Korean hot pot, it is loaded with a variety of ingredients, such as kimchi, tofu, mushrooms and green vegetables. But as you can guess from the title, the highlight of this hot pot is dumplings! Its not just any dumplings. Its super big dumplings, so its very filling! Ultimately, you can use any quality or types of dumplings, but this time I made mine with seafood dumplings. It was filled with real squid, shrimps and so much more. And it was so delicious!',
  'Place the prepared ingredients in a large shallow pot. (FYI, I laid down onion and kimchi at the bottom of the pot, then arranged the remaining ingredients on top, in sections.) Boil the pot over medium high heat until rapidly boiling then reduce the heat to medium low to low. Start serving the dish as individual ingredients get ready. You may turn the heat off at any time. Serve with steamed rice.',
  24,
  4,
  'https://images.pexels.com/photos/5773960/pexels-photo-5773960.jpeg',
  'moderate',
  'korean',
  null,
  19),

  ('Crispy Samosas',
  'Crispy, flaky Samosa is the perfect appetizer for any celebration. Filled with a spicy potato filling, this Samosa is also vegan! The triangular shaped flaky pastry filled with spicy potato, chicken or lamb filling is a popular snack not only in India but in several countries of the world. Because samosa is so so common in India (you literally get samosa and chai at every other street corner), I always considered it to be a quintessential Indian delicacy.',
  'Start by making the samosa dough. To a large bowl, add flour, ajwain (carom seeds), salt and mix well. Add the oil and then start mixing with your fingers. Rub the flour with the oil until the oil is well incorporated in all of the flour. Do this for 3 to 4 minutes, you dont want to rush this step. Once incorporated,  the mixture resembles crumbs. Press some flour between your palm- it should form a shape (& not crumble) - means oil is enough and well incorporated. Now, start adding water, little by little and mix to form a stiff dough. Dont overwork the dough and dont knead a soft dough. It should just come together and form a stiff dough. I used around 6 tablespoons of water here. Cover the dough with a moist cloth and let it rest for 40 minutes. I usually soak a paper towel in water and then squeeze out all the water and then cover my dough with that. While the dough is resting, start working on the filling.',
  112,
  14,
  'https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg',
  'moderate',
  'indian',
  'vegan',
  19),

  ('Souvlaki',
  'This homemade chicken souvlaki recipe takes you to the streets of Athens! Complete with the best souvlaki marinade; instructions for indoor or outdoor grilling; and what to serve with your souvlaki. You simply cannot go to Greece without experiencing souvlaki. Its a major Greek street food, and happens to be one of my favorites.',
  'Prepare the marinade. In the bowl of a small food processor, add garlic, oregano, rosemary, paprika, salt, pepper, olive oil, white wine, and lemon juice (do NOT add the dried bay leaves yet). Pulse until well combined. Place chicken in a large bowl and add bay leaves. Top with marinade. Toss to combine, making sure chicken is well-coated with marinade. cover tightly and refrigerate for 2 hours or overnight (see note for quicker marinating option.) Soak 10 to 12 wooden skewers in water for 30 to 45 minutes or so. Prepare Tzatziki sauce and other fixings, and if youre adding Greek salad or other sides, prepare those as well. (some sides like roasted garlic hummus may take longer, you can prepare those in advance).',
  30,
  6,
  'https://images.pexels.com/photos/5866825/pexels-photo-5866825.jpeg',
  'moderate',
  'greek',
  'lactose-free',
  18),

  ('Seafood Paella',
  'Paella is a Spanish seafood and rice dish, prized for the crispy bits of rice that come from letting the rice sizzle in the pan, and the deep yellow color from saffron. We cheat the color with less expensive ground turmeric and speed the process with precooked brown rice.  Make sure to spread the rice mixture in an even layer so the bottom can crisp. The shrimp take less than 5 minutes to cook. Rinse well under cold running water until completely thawed, and then pat dry before adding to the pan. Serve with simply steamed asparagus to round out the meal.',
  'Heat oil in a large skillet over medium-high. Add turmeric; cook 1 minute, stirring constantly. Add bell pepper, peas, and garlic to pan; cook 2 minutes, stirring occasionally. Stir in rice; spread in an even layer. Cook, without stirring, 3 minutes. Reduce heat to medium. Stir in stock, salt, and pepper. Spread rice mixture in an even layer in pan. Cook, without stirring, 7 minutes. Arrange shrimp on top of rice mixture; cover and cook 3 to 4 minutes or until shrimp are done. Drizzle lemon juice over pan. Serve immediately.',
  45,
  4,
  'https://images.pexels.com/photos/10055897/pexels-photo-10055897.jpeg',
  'challenging',
  'spanish',
  null,
  17),

  ('EVERYDAY MEDITERRANEAN SALAD',
  'This Everyday Mediterranean Salad recipe is quick and easy to make, tossed with a simple Greek vinaigrette, and can easily double as a side salad or main dish. This salad is perfectly balanced with so many of the Mediterranean flavors I love most — peppery arugula, hearty chickpeas, cool cucumbers, smoky roasted reds, tangy feta cheese and a super-simple herby Greek vinaigrette that brings it all together.',
  'Make your dressing. Whisk all of the ingredients together in a small bowl until combined. Or — my preferred method — just add them to a mason jar and shake-shake-shake until the dressing is ready to go. Mix the salad. Then combine all of your salad ingredients in a large mixing bowl. Drizzle evenly with the dressing and toss until combined. Serve. Enjoy right away while it’s nice and fresh!',
  15,
  2,
  'https://images.pexels.com/photos/434258/pexels-photo-434258.jpeg',
  'easy',
  'mediterranean',
  'keto',
  16),

  ('Easy Hummus',
  'This is my favorite hummus recipe! With a few simple tricks, you really can make creamy smooth homemade hummus and yes, we really do think it’s better than store-bought.',
  'In the bowl of a food processor, combine the tahini and lemon juice and process for 1 minute, scrape the sides and bottom of the bowl then process for 30 seconds more. This extra time helps “whip” or “cream” the tahini, making the hummus smooth and creamy. Add the olive oil, minced garlic, cumin, and a 1/2 teaspoon of salt to the whipped tahini and lemon juice. Process for 30 seconds, scrape the sides and bottom of the bowl then process another 30 seconds or until well blended. Open, drain, and rinse the chickpeas. Add half of the chickpeas to the food processor and process for 1 minute. Scrape sides and bottom of the bowl, then add remaining chickpeas and process until thick and quite smooth; 1 to 2 minutes.',
 10,
  6,
  'https://images.pexels.com/photos/6252722/pexels-photo-6252722.jpeg',
  'easy',
  'lebanese',
  'vegan',
  15),

  ('Moroccan Chicken',
  'This right here is the BEST Moroccan Chicken recipe you will find! Super succulent, fall-off-the-bone tender chicken stew w/ warm Moroccan spices, lemons, olives & dried fruit. No ordinary chicken dinner, this easy one-pot wonder will surprise your taste buds in the best way possible. Be sure to watch the video and grab all my tips below!',
  'Heat a bit of quality EVOO over medium high heat until shimmering but  not smoking, then brown the chicken well on both sides. If you left skin on, begin with browning the skin side first, then turn over. Lower heat and add onions, garlic and cilantro. Let those sweat some, then add the lemons, olives, dried fruit. Finally add the liquid. Cover and let cook for 30 to 45 minutes or until chicken is fully cooked through and registers and internal temperature of at least 165 degrees F.',
  65,
  6,
  'https://images.pexels.com/photos/5339083/pexels-photo-5339083.jpeg',
  'moderate',
  'moroccan',
  'low-carb',
  14),

  ('Turkish Pide',
  'Pide is the famous baked Turkish flat bread that comes stuffed with a variety of toppings, including cheese, sausage, spiced meat and spinach. Often described as a Turkish pizza, the greasy, gut-busting takeaway Pides sold at neon-lit corner kebab shops have long been my secret food shame. But shame no more: this delicious homemade Pide recipe trumps takeaway 10 times over - and then some!',
  'Mix instant yeast with warm water and sugar - Once mixed, leave it for 10 minutes to bloom, ie. become foamy. This is not a typical step you see in bread-making when using instant yeast. Usually the whole point of instant yeast is that you can add it straight into dough without mixing with warm water and letting it foam first. But when creating my naan recipe, we found that blooming instant yeast in a warm water and sugar solution first makes flatbreads fluffier and softer. Its also an excellent safety test to ensure your yeast is still alive. Foamy yeast in water = alive, no foam = dead yeast! Thats right, dried yeast stored in a jar eventually dies (thats what the expiry means - but actually it starts to degrade well before that). Nothing is worse than discovering your yeast is dead by taking out a cooked bread loaf from the oven thats rock hard and flat! Foam test - So we do our yeast foam test to avoid all this potential heartbreak. This is what it looks like after 10 minutes. Foamy, good!',
  182,
  2,
  'https://images.pexels.com/photos/7813736/pexels-photo-7813736.jpeg',
  'challenging',
  'turkish',
  null,
  13),

  ('Curry Shrimp Soup',
  'Cook an incredible dinner with minimal ingredients with our Shrimp Curry recipe. A coconut curry sauce made with minimal ingredients simmers around tender shrimp makes for an incredible dinner. Youll be surprised at how GOOD this is! Make this shrimp curry even more spectacular and serve it with super soft Naan bread to mop up the sauce!',
  'Heat remaining oil and butter in a large pan or skillet over medium-high heat. Fry onion until soft (about 3 minutes), scraping up any browned bits left over from the shrimp on the bottom of the pan. Add garlic and ginger; sauté until fragrant, about for 1 minute. Add in garam masala, cumin, ground coriander and turmeric (or curry powder). Cook stirring occasionally until fragrant, about 20 seconds. Add crushed tomatoes (or Passata), chili powder, salt, sugar and coconut milk/cream. Let simmer until slightly thickened, about 4 minutes. Stir in shrimp and let cook until the shrimp is fully cooked and warmed through, about 1 more minute. Take off the heat immediately. Garnish with chopped cilantro and serve with fresh garlic butter rice and homemade naan bread.',
  32,
  4,
  'https://images.pexels.com/photos/1437590/pexels-photo-1437590.jpeg',
  'moderate',
  'thai',
  null,
  12),

  ('Easy Lo Mein',
  'The easiest lo mein you will ever make in 15 minutes from start to finish. It is so much quicker, tastier and healthier than take-out! These are directions. Back when I had a day job, I had this boss who was obsessed with the lo mein from the restaurant across the street. She would have me order it at least 3 times a week, and I would get so excited because she would always pass along a plate for me to share.',
  'In a small bowl, whisk together soy sauce, sugar, sesame oil, ginger and Sriracha; set aside. In a large pot of boiling water, cook noodles according to package instructions; drain well. Heat olive oil in a large skillet or wok over medium high heat. Add garlic, mushrooms, bell pepper and carrot. Cook, stirring frequently, until tender, about 3-4 minutes. Stir in snow peas and spinach until the spinach has wilted, about 2-3 minutes. Stir in egg noodles and soy sauce mixture, and gently toss to combine. Serve immediately.',
  18,
  4,
  'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg',
  'easy',
  'chinese',
  'vegetarian',
  11),

  ('Homemade Sushi',
  'Homemade Sushi is so much cheaper than at the restaurant. Sushi is easy and fun to make at home, and you can put all your favorite ingredients into your perfect custom roll — heres how! Ill be very honest and say that theres definitely a reason why chefs spend a decade learning how to perfect sushi rice or cut raw fish like a boss, because it does make a difference.',
  'Place the seaweed on a bamboo mat, then cover the sheet of seaweed with an even layer of prepared sushi rice. Smooth gently with the rice paddle. Layer salmon, cream cheese, and avocado on the rice, and roll it up tightly. Slice with a sharp knife, and enjoy with soy sauce.',
  20,
  6,
  'https://images.pexels.com/photos/248444/pexels-photo-248444.jpeg',
  'easy',
  'japanese',
  null,
  10),

  ('Baklava',
  'This honey baklava is flaky, crisp and tender and I love that it isnt overly sweet. Its basically a party in your mouth. I am a huge fan of baklava and this is the BEST baklava recipe I have ever tried. Hands down. You will love the hint of mellow lemony flavor which offsets the sweetness and compliments the cinnamon. Its truly delicious. Store-bought baklava has nothing on this and trust me, Ive been around the block when shopping for baklava. This baklava recipe is well loved wherever it goes and it is definitely a reader and family favorite!',
  'Thaw phyllo dough according to package instructions (this is best done overnight in the fridge, then place it on the counter for 1 hour before starting your recipe to bring it to room temp). Trim phyllo dough to fit your baking sheet. My phyllo dough package had 2 rolls with a total of 40 sheets that measured 9x14 so I had to trim them slightly. You can trim one stack at a time then cover with a damp towel to keep from drying out. Butter the bottom and sides of a 13x9 non-stick baking pan.',
  75,
  30,
  'https://images.pexels.com/photos/10038700/pexels-photo-10038700.jpeg',
  'moderate',
  'turkish',
  'lactose-free',
  9),

  ('Homemade Pizza',
  'This is a classic homemade pizza recipe, including a pizza dough recipe, topping suggestions, and step-by-step instructions with photos. Make perfect pizza at home! What to do when your 8-year old nephew comes to visit? Make pizza, of course! Well, not of course, actually. I didnt think of it until we exhausted Sorry, Monopoly, and gin rummy. But it did turn out to be a brilliant idea as my father had just received a baking stone for Christmas, and my nephew loves pizza. I told him if he helped me make it I would talk about him on my website and he would be famous. That seemed to get his attention. He thought the dough was "slimy and gross" but he loved picking his own toppings, and the finished product was "awesome".',
  'Place the warm water in the large bowl of a heavy duty stand mixer. Sprinkle the yeast over the warm water and let it sit for 5 minutes until the yeast is dissolved. After 5 minutes stir if the yeast hasnt dissolved completely. The yeast should begin to foam or bloom, indicating that the yeast is still active and alive. (Note that if you are using "instant yeast" instead of "active yeast", no proofing is required. Just add to the flour in the next step.)',
  150,
  4,
  'https://images.pexels.com/photos/842519/pexels-photo-842519.jpeg',
  'easy',
  'italian',
  null,
  9),


  ('Chicken Provencal',
  'There are quite possibly hundreds of variations on braising chicken in wine, but classic Chicken Provencal is definitely one of my favorites. While I find it to be a stunning presentation, the skillet of juicy chicken braised in wine and dotted with flavorful add-ins is comfort food at its best. Shallots, garlic, tomatoes, herbs, and a citrusy white wine all add to the flavor in this dish.
  Since this is a classic braised recipe (meaning that majority of the cooking is in liquid in the oven) there is very little chance of the meat drying out and the dish ends up as a classic one-pot dinner.
  The time on this recipe might seem daunting since it takes over an hour from start to finish but remember that almost all of it is hands off. That said, I usually save Chicken Provencal for the weekends, so I dont feel rushed and let the braise do its magic in the oven. Once the skillet is in the oven, you can relax with a glass of wine and know that you will have a very special dinner ready in no time.',
  'Preheat the oven: Preheat the oven to 400°F. Season and sauté the chicken: Season the chicken thighs well on all side with salt and pepper. In a large (at least 12-inch) oven-safe skillet or Dutch oven over medium-low heat, add olive oil. Add chicken thighs into the skillet, skin side down. Cook, untouched, for 8-10 minutes so skin can start to render and brown slowly. While your chicken thighs start to brown, prepare the other ingredients.', 
  85,
  6,
  'https://vikalinka.com/wp-content/uploads/2017/01/IMG_8797-Edit.jpg',
  'easy',
  'spanish',
  'kosher',
  3),

  ('Beef Bulgogi',
  'It was always a treat when my mom would whip this up on those busy weeknights - marinating the beef just a few hours while I was at swim practice. And then shed throw these onto a hot skillet, filling up the house with the best kind of beef aroma - you know, the smell at the Korean BBQ restaurants that get you so hungry. The key here is to slice the meat as thin as possible. Throwing the steak in the freezer for 20-30 minutes helps with this process tremendously. That way, the thin cuts of meat can soak up the most epic marinade in just a few hours.',
  'Wrap steak in plastic wrap, and place in the freezer for 30 minutes. Unwrap and slice across the grain into 1/4-inch thick slices. In a medium bowl, combine pear, soy sauce, brown sugar, sesame oil, garlic, ginger and gochujang. In a gallon size Ziploc bag, combine soy sauce mixture and steak; marinate for at least 2 hours to overnight, turning the bag occasionally. Heat 1 tablespoon vegetable oil in a cast iron grill pan over medium-high heat.* Working in batches, add steak to the grill pan in a single layer and cook, flipping once, until charred and cooked through, about 2-3 minutes per side. Repeat with remaining 1 tablespoon vegetable oil and steak. Serve immediately, garnished with green onions and sesame seeds, if desired.',
  120,
  6,
  'https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg',
  'challenging',
  'korean',
  null,
  7),

  ('Vegan Tzatziki',
  'Tzatziki is a cucumber and yogurt-based sauce or dip commonly served in Greek cuisine. Its thought to have been inspired by a similar Indian sauce called raita. Our plant-based version is similarly cool and creamy, but made without the dairy! Simply mix all together and there you have it! Creamy, tangy, delicious tzatziki ready to be spread on all the things.',
  'Finely grate cucumber with the skin on - should yield about 1 cup (amount as original recipe is written // adjust if altering batch size). Then either set in a fine-mesh strainer set over a small mixing bowl or transfer to a clean, thin towel and squeeze out excess moisture. The remaining amount should be about 1/4 cup (amount as original recipe is written // adjust if altering batch size). Add coconut yogurt to a large mixing bowl and add strained cucumber, garlic, dill, salt, pepper, lemon juice, and olive oil (optional). Stir to combine. Taste and adjust flavor as needed, adding more salt for overall flavor, garlic for zing, lemon for acidity, or dill for herbiness. Serve immediately, or store in the refrigerator (where it will thicken) up to 5 days, sometimes longer depending on freshness of yogurt.',
  10,
  7,
  'https://minimalistbaker.com/wp-content/uploads/2017/08/AMAZING-Vegan-Tzatziki-5-ingredients-THICK-flavorful-The-perfect-sauce-for-Greek-night.-yogurt-tzatziki-recipe-vegan-glutenfree-minimalistbaker-7.jpg',
  'easy',
  'greek',
  'vegan',
  5),

  ('Channa Masala',
  'Chana masala, also called chole masala, is believed to have originated in northern India. "Chana" means chickpea and "masala" refers to a blend of spices used in Indian cooking. Its a popular dish throughout India and Pakistan, with recipes varying by region. And its also gained popularity around the world. The following is our inspired version resembling what weve tasted in restaurants. Our version is made with green chilies, onion, garlic, fresh cilantro, a blend of spices, chickpeas, and tomatoes. It can be prepared a number of different ways, but I chose the simple route: 1 pot and about 30 minutes required.',
  'Heat a large pot over medium heat. Once hot, add oil, onion, cumin, and one-third of the salt (1/4 tsp as original recipe is written // adjust if altering batch size). Add garlic, ginger, cilantro, and green chilies to a mortar and pestle and grind into a rough paste (or use a small food processor to pulse into a paste. Alternatively, just finely mince.) Then, add to the pan with the onions. Next add ground coriander, chili powder, and turmeric and stir to coat. Add a little more oil at this point if the pan is looking dry. Next add pureed tomatoes and chickpeas and remaining salt (1/2 tsp as original recipe is written). If the mixture looks a little too thick, add up to 1 cup (240 ml) water (I added ~1/2 cup (120 ml) // amount as original recipe is written // adjust if altering batch size). Youre looking for a semi-thick soup consistency at this point, as it will cook down into more of a stew. Increase heat to medium high until it reaches a rolling simmer, then reduce heat to low or medium-low and maintain a simmer (uncovered) for 15-20 minutes, or until thick and stew-like. Stir occasionally.',
  30,
  6,
  'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg',
  'easy',
  'indian',
  'vegan',
  4),

  ('Crispy Tofu',
  'This Crispy Tofu recipe is all about textural contrast: the crispy outer coating vs. the soft, tender interior of the soft tofu itself. I serve it drizzled with a quick sauce, reduced down until thick and syrupy, and fresh scallions. The best part? No deep-frying necessary! The secret to making crispy tofu without deep-frying is simply to pan-fry in a good nonstick or well-seasoned cast iron pan. Youll use a fraction of the oil, but still end up with a crispy result. I dredge the tofu in a simple mixture of cornstarch and a little salt. Its important to dredge the tofu quickly, and to put it directly into the pan of hot oil as you dredge it. Otherwise, the moisture in the soft tofu (soft tofu is quite wet) will cause the cornstarch to cake up and flake off. Or the cornstarch layer could get overly lumpy or too thick!',
  'Slice the block of tofu in half lengthwise, then slice into 1/2 inch thick rectangles. Make the sauce by combining the light soy sauce, dark soy sauce, oyster sauce (or vegetarian oyster sauce), sugar, and water. Set aside. Heat a non-stick pan over medium heat, and add the oil. In a shallow dish, mix 1/4 cup cornstarch with 1/2 teaspoon salt. Quickly coat the tofu slices with this dry mixture. Add them directly to the pan as you dredge them, and pan-fry until crisp and golden on both sides, about 4-5 minutes per side. Remove the crispy tofu from the pan and arrange on a serving plate. Pour the sauce mixture into the same pan you cooked the tofu in, and bring to a simmer. Simmer until the sauce has reduced to a syrupy consistency and drizzle over the tofu. Garnish with chopped scallion.',
  25,
  4,
  'https://images.pexels.com/photos/6655415/pexels-photo-6655415.jpeg',
  'easy',
  'chinese',
  'low-carb',
  2),

  ('Good Old Fashioned Pancakes',
  'This is a great recipe that I found in my Grandmas recipe book. Judging from the weathered look of this recipe card, this was a family favorite. Delicious, easy and good for you! Blueberries and chia seeds added to a simple pancake recipe boost the goodness and the flavor. Thats whats for breakfast! Serve warm with maple syrup.',
  'In a large bowl, sift together the flour, baking powder, salt and sugar. Make a well in the center and pour in the milk, egg and melted butter; mix until smooth. Heat a lightly oiled griddle or frying pan over medium-high heat. Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.',
  20,
  8, 'https://images-gmi-pmc.edge-generalmills.com/df109202-f5dd-45a1-99b4-f10939afd509.jpg',
  'easy',
  'american',
  null,
  1),

  ('Aji De Gallina',
  'Peruvian cuisine is starting to gain recognition, thanks to a new generation of chefs who are digging into their roots and bringing back the classic dishes of their youth to a broader audience of adventurous eaters around the world. Many of these chefs are the so-called first generation in the United States and have had the chance to learn firsthand all the classic dishes from their moms and abuelas (grandmothers). Ají de gallina is one of these traditional dishes: Poached chicken slathered in a spicy and creamy nut-based sauce is served over white rice and boiled potatoes. Bright yellow—amarillo—in color, thanks to the famous ají amarillo, and rich from the unusual sauce of ground walnuts, this dish is hearty, filling, and delicious. Dont be intimidated by how complex it sounds, the recipe is broken down into bite-sized pieces and is well worth the effort.',
  'Gather the ingredients. Ingredients for ají de gallina spicy creamed chicken Cook the yellow potatoes in salted water until tender when pierced with a fork. Potatoes boiling in a pot Let cool, peel, cut into quarters, and set aside. Boiled, cut potatoes place the bread in a small bowl and pour the 3/4 cup of evaporated milk over it to soak. Set aside. Sliced bread soaking in milk. Place the chicken in a pot with the chicken stock and bring to a simmer. Chicken breasts boiling. Cook for 10 to 15 minutes until chicken is just barely cooked through. Chicken breasts boiling. Set chicken aside to cool, reserving the stock. Chicken breasts and broth. Strain the stock and reserve 2 cups. Bowl of broth with strainer. Shred the cooled chicken into bite-sized pieces. Shredded chicken Remove stems and seeds from the peppers. Sliced yellow peppers In a blender, process the peppers with vegetable oil. Blend until smooth. Blended peppers with vegetable oil',
  60,
  6,
  'https://keeprecipes.com/sites/keeprecipes/files/aji-de-gallina.jpg',
  'moderate',
  'spanish',
  null,
  1),

  ('Classic Burger',
  'Sink your teeth into a delicious restaurant-style, hamburger recipe made from lean beef. Skip the prepackaged patties and take the extra time to craft up your own, and that little extra effort will be worth it. To make cheeseburgers, about 1 minute before burgers are done, top with sliced cheese; continue cooking until cheese begins to melt.',
  'In a bowl, mix ground beef, egg, onion, bread crumbs, Worcestershire, garlic, 1/2 teaspoon salt, and 1/4 teaspoon pepper until well blended. Divide mixture into four equal portions and shape each into a patty about 4 inches wide. Lay burgers on an oiled barbecue grill over a solid bed of hot coals or high heat on a gas grill (you can hold your hand at grill level only 2 to 3 seconds); close lid on gas grill. Cook burgers, turning once, until browned on both sides and no longer pink inside (cut to test), 7 to 8 minutes total. Remove from grill. Lay buns, cut side down, on grill and cook until lightly toasted, 30 seconds to 1 minute. Spread mayonnaise and ketchup on bun bottoms. Add lettuce, tomato, burger, onion, and salt and pepper to taste. Set bun tops in place.',
  30,
  4,
  'https://images.pexels.com/photos/3616956/pexels-photo-3616956.jpeg',
  'moderate',
  'american',
  'kosher',
  12)
  ;