INSERT INTO
ingredients(ingredient_name, amount, recipe_id)
VALUES
  ('Sauce - Black Current, Dry Mix', '4 units', 157),
  ('Longan', '3 units', 91),
  ('Buffalo - Short Rib Fresh', '10 units', 100),
  ('Seedlings - Clamshell', '8 units', 31),
  ('Chocolate - Pistoles, Lactee, Milk', '8 units', 80),
  ('Meldea Green Tea Liquor', '2 units', 96),
  ('Oil - Olive, Extra Virgin', '6 units', 138),
  ('Soup - Campbells, Minestrone', '5 units', 1),
  ('Bread - Dark Rye, Loaf', '2 units', 110),
  ('Puff Pastry - Sheets', '4 units', 62),
  ('Wine - Sicilia Igt Nero Avola', '2 units', 56),
  ('Appetizer - Tarragon Chicken', '7 units', 177),
  ('Celery Root', '9 units', 144),
  ('Sauce - Rosee', '1 units', 129),
  ('Cognac - Courvaisier', '5 units', 67),
  ('Pepper - Black, Crushed', '2 units', 132),
  ('Sprouts - Alfalfa', '4 units', 53),
  ('Venison - Striploin', '5 units', 114),
  ('Brandy - Bar', '3 units', 142),
  ('Water - Spring Water 500ml', '9 units', 68),
  ('Coconut - Whole', '5 units', 196),
  ('Curry Powder', '1 units', 106),
  ('Baking Soda', '9 units', 180),
  ('Beans - Turtle, Black, Dry', '2 units', 19),
  ('Wine - Mondavi Coastal Private', '10 units', 184),
  ('Sauce - Balsamic Viniagrette', '6 units', 122),
  ('Sauce - Mint', '7 units', 200),
  ('Sauce - Salsa', '3 units', 180),
  ('Wine - Pinot Noir Pond Haddock', '5 units', 11),
  ('Cheese - Grie Des Champ', '2 units', 109),
  ('Bread - Bagels, Mini', '4 units', 90),
  ('Spice - Peppercorn Melange', '4 units', 179),
  ('Olives - Morracan Dired', '5 units', 60),
  ('Water - Mineral, Natural', '2 units', 142),
  ('Yogurt - Banana, 175 Gr', '5 units', 156),
  ('Rice - 7 Grain Blend', '9 units', 37),
  ('Pastrami', '10 units', 126),
  ('Couscous', '6 units', 176),
  ('Mangoes', '5 units', 131),
  ('Tobasco Sauce', '6 units', 13),
  ('Veal - Chops, Split, Frenched', '3 units', 130),
  ('Ranchero - Primerba, Paste', '2 units', 190),
  ('Wine - George Duboeuf Rose', '9 units', 147),
  ('Egg - Salad Premix', '7 units', 117),
  ('Kahlua', '6 units', 45),
  ('Compound - Strawberry', '4 units', 53),
  ('Soup - Campbells, Spinach Crm', '4 units', 78),
  ('Water Chestnut - Canned', '6 units', 146),
  ('Miso - Soy Bean Paste', '1 units', 1),
  ('Bay Leaf Ground', '1 units', 139),
  ('Dc - Sakura Fu', '4 units', 61),
  ('Wine - Barossa Valley Estate', '3 units', 157),
  ('Beans - Yellow', '5 units', 195),
  ('Edible Flower - Mixed', '5 units', 164),
  ('Glass Clear 7 Oz Xl', '5 units', 83),
  ('Wild Boar - Tenderloin', '2 units', 8),
  ('Kolrabi', '7 units', 11),
  ('Veal - Bones', '6 units', 175),
  ('Trout - Rainbow, Frozen', '2 units', 55),
  ('Skirt - 24 Foot', '8 units', 141),
  ('Garbage Bags - Clear', '7 units', 93),
  ('Blouse / Shirt / Sweater', '9 units', 71),
  ('Icecream - Dibs', '8 units', 191),
  ('Veal - Liver', '5 units', 38),
  ('Cheese - Marble', '3 units', 94),
  ('Mushroom - Enoki, Dry', '6 units', 15),
  ('Tart Shells - Sweet, 4', '3 units', 171),
  ('Sloe Gin - Mcguinness', '10 units', 40),
  ('Wine - Balbach Riverside', '9 units', 33),
  ('Juice - Ocean Spray Kiwi', '5 units', 184),
  ('Vodka - Hot, Lnferno', '3 units', 185),
  ('Towel Multifold', '7 units', 58),
  ('Pears - Anjou', '8 units', 4),
  ('Pasta - Cappellini, Dry', '3 units', 143),
  ('Beans - Fava, Canned', '6 units', 33),
  ('Wine - Guy Sage Touraine', '3 units', 123),
  ('Mushroom - Porcini, Dry', '5 units', 9),
  ('Chinese Foods - Thick Noodles', '8 units', 137),
  ('Lettuce - Spring Mix', '10 units', 138),
  ('Orange - Canned, Mandarin', '9 units', 54),
  ('Cheese Cloth No 60', '6 units', 187),
  ('Bay Leaf Ground', '10 units', 28),
  ('Lychee - Canned', '3 units', 151),
  ('Pork - Bacon, Sliced', '1 units', 27),
  ('Pepper - Scotch Bonnet', '5 units', 116),
  ('Wine - Touraine Azay - Le - Rideau', '2 units', 16),
  ('Trueblue - Blueberry Cranberry', '7 units', 44),
  ('Cheese - Cheddar, Old White', '8 units', 178),
  ('Triple Sec - Mcguinness', '7 units', 50),
  ('Quail - Eggs, Fresh', '5 units', 46),
  ('Pork - Bacon, Double Smoked', '9 units', 35),
  ('Muffin Mix - Raisin Bran', '3 units', 30),
  ('Water Chestnut - Canned', '5 units', 69),
  ('Pasta - Orzo, Dry', '3 units', 185),
  ('Crab - Dungeness, Whole', '10 units', 126),
  ('Foil - Round Foil', '1 units', 55),
  ('Lettuce - Belgian Endive', '6 units', 71),
  ('Butter - Pod', '6 units', 196),
  ('Kolrabi', '9 units', 19),
  ('Appetizer - Tarragon Chicken', '8 units', 149),
  ('Chocolate - Milk Coating', '2 units', 43),
  ('Juice - Tomato, 10 Oz', '5 units', 184),
  ('Tortillas - Flour, 8', '5 units', 40),
  ('Vacuum Bags 12x16', '10 units', 112),
  ('7up Diet, 355 Ml', '4 units', 195),
  ('Pasta - Fettuccine, Dry', '8 units', 149),
  ('Scallops 60/80 Iqf', '7 units', 136),
  ('Wine - Rosso Toscano Igt', '5 units', 27),
  ('Wine - Red, Wolf Blass, Yellow', '4 units', 9),
  ('Coffee - Flavoured', '2 units', 170),
  ('Crab - Blue, Frozen', '6 units', 191),
  ('Wine - Gato Negro Cabernet', '3 units', 173),
  ('Wine - Stoneliegh Sauvignon', '7 units', 68),
  ('Haggis', '5 units', 125),
  ('Tarragon - Fresh', '4 units', 172),
  ('Cheese - Cambozola', '4 units', 19),
  ('Wine - Rioja Campo Viejo', '3 units', 124),
  ('Bagel - Whole White Sesame', '4 units', 172),
  ('Munchies Honey Sweet Trail Mix', '6 units', 103),
  ('Spice - Paprika', '9 units', 105),
  ('Soup - Campbells Pasta Fagioli', '10 units', 21),
  ('Lamb - Leg, Boneless', '3 units', 195),
  ('Shark - Loin', '2 units', 14),
  ('Wine - Chablis J Moreau Et Fils', '8 units', 97),
  ('Beer - Maudite', '2 units', 72),
  ('Numi - Assorted Teas', '10 units', 98),
  ('Veal - Provimi Inside', '3 units', 37),
  ('Puree - Passion Fruit', '6 units', 128),
  ('Turnip - Mini', '2 units', 136),
  ('Green Scrubbie Pad H.duty', '6 units', 92),
  ('Mace Ground', '4 units', 145),
  ('Lamb Tenderloin Nz Fr', '10 units', 129),
  ('Napkin Colour', '8 units', 74),
  ('Wine - Stoneliegh Sauvignon', '4 units', 137),
  ('Water - Spring Water, 355 Ml', '1 units', 49),
  ('Marsala - Sperone, Fine, D.o.c.', '7 units', 75),
  ('Rabbit - Whole', '8 units', 45),
  ('Eggplant - Asian', '10 units', 28),
  ('Crackers - Water', '7 units', 1),
  ('Daves Island Stinger', '10 units', 2),
  ('Placemat - Scallop, White', '8 units', 94),
  ('Ginger - Ground', '9 units', 33),
  ('Wine - Pinot Noir Latour', '10 units', 184),
  ('Ham - Virginia', '9 units', 28),
  ('Dehydrated Kelp Kombo', '8 units', 3),
  ('Bread - Raisin', '7 units', 186),
  ('Wine - Prosecco Valdobiaddene', '5 units', 139),
  ('Wine - Magnotta - Cab Franc', '5 units', 31),
  ('Bread - Mini Hamburger Bun', '5 units', 136),
  ('Yogurt - French Vanilla', '9 units', 150),
  ('Island Oasis - Banana Daiquiri', '1 units', 142),
  ('Carrots - Jumbo', '5 units', 136),
  ('Melon - Watermelon Yellow', '8 units', 71),
  ('Cheese - Parmigiano Reggiano', '4 units', 166),
  ('Table Cloth 81x81 Colour', '4 units', 140),
  ('Soup - Campbells Mac N Cheese', '4 units', 75),
  ('Sauce - Vodka Blush', '6 units', 44),
  ('Wine - White, French Cross', '9 units', 9),
  ('Cheese - Cheddar, Old White', '10 units', 46),
  ('Sobe - Cranberry Grapefruit', '10 units', 46),
  ('Veal - Inside', '7 units', 178),
  ('Nantucket - Orange Mango Cktl', '3 units', 12),
  ('Bacardi Breezer - Tropical', '7 units', 163),
  ('Lettuce - Lolla Rosa', '4 units', 123),
  ('Bread - Corn Muffaleta Onion', '3 units', 154),
  ('Cherries - Fresh', '10 units', 80),
  ('Soup Campbells - Tomato Bisque', '6 units', 1),
  ('Pork - Bacon, Double Smoked', '4 units', 174),
  ('Blueberries', '7 units', 88),
  ('Noodles - Steamed Chow Mein', '4 units', 77),
  ('Dasheen', '5 units', 4),
  ('Soup - Campbells, Classic Chix', '10 units', 75),
  ('Beef - Rib Eye Aaa', '9 units', 83),
  ('Table Cloth 144x90 White', '6 units', 197),
  ('Soup - Campbells, Spinach Crm', '8 units', 55),
  ('Bagelers - Cinn / Brown', '9 units', 147),
  ('Savory', '1 units', 42),
  ('Eggplant Italian', '8 units', 97),
  ('Bread - Flat Bread', '10 units', 74),
  ('Wine - White, Riesling, Henry Of', '9 units', 100),
  ('Beer - Camerons Cream Ale', '4 units', 172),
  ('Chicken - Wings, Tip Off', '10 units', 11),
  ('Persimmons', '8 units', 19),
  ('Tea - Orange Pekoe', '9 units', 131),
  ('Smoked Paprika', '3 units', 140),
  ('Sour Cream', '9 units', 19),
  ('Coffee - Frthy Coffee Crisp', '5 units', 178),
  ('English Muffin', '3 units', 174),
  ('Lid - 0090 Clear', '1 units', 163),
  ('Onions - Cippolini', '2 units', 115),
  ('Sauce - Bernaise, Mix', '4 units', 131),
  ('Beans - Wax', '2 units', 174),
  ('Juice - Clamato, 341 Ml', '3 units', 152),
  ('Chocolate Bar - Coffee Crisp', '1 units', 82),
  ('Lumpfish Black', '8 units', 3),
  ('Tea - Green', '9 units', 140),
  ('Spinach - Frozen', '10 units', 40),
  ('Juice - Pineapple, 48 Oz', '4 units', 155),
  ('Island Oasis - Lemonade', '7 units', 151),
  ('Snapple - Mango Maddness', '3 units', 63),
  ('Kahlua', '10 units', 120),
  ('Bread Sour Rolls', '2 units', 193),
  ('Bread - Roll, Soft White Round', '10 units', 154),
  ('Lumpfish Black', '9 units', 39),
  ('Tea - Honey Green Tea', '1 units', 28),
  ('Sauce - Apple, Unsweetened', '7 units', 16),
  ('Eggwhite Frozen', '5 units', 190),
  ('Thermometer Digital', '1 units', 187),
  ('Sugar - Cubes', '6 units', 143),
  ('Mints - Striped Red', '9 units', 22),
  ('Sauce - Apple, Unsweetened', '2 units', 190),
  ('Sobe - Berry Energy', '7 units', 128),
  ('Bread - Multigrain', '10 units', 16),
  ('Wine - Red, Cooking', '9 units', 182),
  ('Piping Jelly - All Colours', '5 units', 66),
  ('Anchovy Fillets', '4 units', 102),
  ('Tea - Earl Grey', '3 units', 104),
  ('Swiss Chard', '7 units', 97),
  ('Pasta - Penne, Lisce, Dry', '6 units', 73),
  ('Daikon Radish', '6 units', 137),
  ('Flower - Carnations', '4 units', 124),
  ('Chicken Breast Halal', '10 units', 100),
  ('Parsley Italian - Fresh', '3 units', 180),
  ('Wine - White Cab Sauv.on', '10 units', 39),
  ('Syrup - Pancake', '9 units', 169),
  ('Daves Island Stinger', '7 units', 11),
  ('Shortbread - Cookie Crumbs', '10 units', 189),
  ('Cranberries - Frozen', '4 units', 140),
  ('Star Fruit', '7 units', 104),
  ('Wine - White, Mosel Gold', '10 units', 167),
  ('Wine - Sauvignon Blanc', '3 units', 48),
  ('Tart Shells - Sweet, 3', '6 units', 10),
  ('Foam Espresso Cup Plain White', '3 units', 56),
  ('Lettuce - Radicchio', '5 units', 47),
  ('Chambord Royal', '5 units', 12),
  ('Milk - Chocolate 250 Ml', '6 units', 102),
  ('Turkey - Breast, Double', '3 units', 16),
  ('Lemonade - Black Cherry, 591 Ml', '4 units', 145),
  ('Rabbit - Legs', '10 units', 164),
  ('Durian Fruit', '9 units', 9),
  ('Cabbage - Nappa', '6 units', 15),
  ('Sole - Fillet', '10 units', 126),
  ('Tea - Orange Pekoe', '7 units', 107),
  ('Shark - Loin', '2 units', 190),
  ('Eggplant Oriental', '1 units', 156),
  ('Wine - Fume Blanc Fetzer', '1 units', 187),
  ('Pasta - Canelloni', '1 units', 82),
  ('Appetizer - Mushroom Tart', '1 units', 117),
  ('Goulash Seasoning', '7 units', 68),
  ('Cheese - Cheddar, Old White', '2 units', 122),
  ('Wine - Red, Lurton Merlot De', '7 units', 165),
  ('Trout - Rainbow, Frozen', '6 units', 199),
  ('Eel - Smoked', '9 units', 179),
  ('Numi - Assorted Teas', '10 units', 132),
  ('Ecolab - Lime - A - Way 4/4 L', '3 units', 188),
  ('Chocolate - Mi - Amere Semi', '6 units', 126),
  ('Doilies - 8, Paper', '6 units', 160),
  ('Tarragon - Primerba, Paste', '5 units', 200),
  ('Wine - Magnotta - Cab Sauv', '2 units', 104),
  ('Milk - Homo', '7 units', 107),
  ('Wine - Guy Sage Touraine', '3 units', 143),
  ('Hickory Smoke, Liquid', '3 units', 187),
  ('Bread - Focaccia Quarter', '6 units', 170),
  ('Split Peas - Yellow, Dry', '7 units', 34),
  ('Bread - Bagels, Plain', '3 units', 26),
  ('Laundry - Bag Cloth', '10 units', 173),
  ('Juice - Orange', '10 units', 62),
  ('Lettuce - Green Leaf', '7 units', 50),
  ('Wine - Toasted Head', '5 units', 31),
  ('Table Cloth 54x54 White', '10 units', 166),
  ('Oil - Avocado', '4 units', 7),
  ('Pesto - Primerba, Paste', '7 units', 15),
  ('Chinese Foods - Cantonese', '7 units', 9),
  ('Sour Puss - Tangerine', '8 units', 68),
  ('Cleaner - Comet', '10 units', 35),
  ('Wine - Lou Black Shiraz', '5 units', 181),
  ('Nori Sea Weed - Gold Label', '5 units', 44),
  ('Cilantro / Coriander - Fresh', '6 units', 142),
  ('Wine - Clavet Saint Emilion', '8 units', 109),
  ('Bread - Bistro Sour', '8 units', 193),
  ('Pie Pecan', '10 units', 17),
  ('Lettuce - Romaine', '1 units', 82),
  ('Pasta - Angel Hair', '9 units', 188),
  ('Propel Sport Drink', '1 units', 35),
  ('Ice Cream - Vanilla', '5 units', 24),
  ('Tuna - Loin', '7 units', 74),
  ('Tomato - Plum With Basil', '5 units', 142),
  ('Carbonated Water - Blackcherry', '8 units', 119),
  ('Cake - Bande Of Fruit', '5 units', 137),
  ('Trueblue - Blueberry 12x473ml', '6 units', 26),
  ('Wine - Peller Estates Late', '1 units', 147),
  ('Juice - Apple, 1.36l', '3 units', 62),
  ('Muffin - Mix - Creme Brule 15l', '4 units', 140),
  ('Pork Loin Cutlets', '4 units', 43),
  ('Cloves - Ground', '6 units', 9),
  ('Crackers - Soda / Saltins', '7 units', 42),
  ('Fish - Artic Char, Cold Smoked', '10 units', 1),
  ('Salt - Celery', '7 units', 166),
  ('Juice - Pineapple, 341 Ml', '7 units', 134),
  ('Onions - Cippolini', '6 units', 79),
  ('Petit Baguette', '7 units', 27),
  ('Beer - Original Organic Lager', '4 units', 194),
  ('Wine - Red, Lurton Merlot De', '2 units', 61),
  ('Pork - Tenderloin, Frozen', '9 units', 93),
  ('Venison - Denver Leg Boneless', '2 units', 81),
  ('Cheese - Cottage Cheese', '7 units', 88),
  ('Crackers - Soda / Saltins', '3 units', 79),
  ('Muffin Carrot - Individual', '4 units', 33),
  ('Corn Kernels - Frozen', '7 units', 104),
  ('Sambuca Cream', '2 units', 185),
  ('Container - Clear 32 Oz', '1 units', 145),
  ('Quail - Whole, Boneless', '7 units', 135),
  ('Evaporated Milk - Skim', '4 units', 96),
  ('Sprouts - Onion', '5 units', 134),
  ('Cabbage - Nappa', '1 units', 63),
  ('Wine - Casillero Del Diablo', '6 units', 144),
  ('Mushroom - Morels, Dry', '10 units', 182),
  ('Salt And Pepper Mix - White', '8 units', 133),
  ('Squid - Tubes / Tenticles 10/20', '4 units', 167),
  ('Hand Towel', '5 units', 95),
  ('Blackberries', '9 units', 134),
  ('Lamb - Whole, Fresh', '3 units', 145),
  ('Beef - Top Sirloin', '10 units', 140),
  ('Syrup - Monin, Amaretta', '3 units', 87),
  ('Cheese - Parmesan Grated', '6 units', 96),
  ('Juice - Pineapple, 48 Oz', '10 units', 115),
  ('Dip - Tapenade', '5 units', 78),
  ('Cheese - Goat With Herbs', '6 units', 198),
  ('Pepper - White, Ground', '1 units', 59),
  ('Wine - Coteaux Du Tricastin Ac', '3 units', 35),
  ('Breakfast Quesadillas', '6 units', 72),
  ('Veal - Chops, Split, Frenched', '8 units', 177),
  ('Wine - Chateauneuf Du Pape', '4 units', 173),
  ('Oxtail - Cut', '5 units', 9),
  ('Island Oasis - Sweet And Sour Mix', '3 units', 29),
  ('Tart - Pecan Butter Squares', '3 units', 145),
  ('Pasta - Shells, Medium, Dry', '10 units', 77),
  ('Bagelers - Cinn / Brown Sugar', '2 units', 41),
  ('Salmon - Smoked, Sliced', '2 units', 153),
  ('Appetizer - Sausage Rolls', '9 units', 10),
  ('Juice - Lagoon Mango', '10 units', 12),
  ('Tea - Darjeeling, Azzura', '8 units', 176),
  ('Figs', '8 units', 96),
  ('Wine - Savigny - Les - Beaune', '2 units', 92),
  ('Rhubarb', '1 units', 149),
  ('Appetizer - Tarragon Chicken', '8 units', 155),
  ('Initation Crab Meat', '2 units', 193),
  ('Oil - Grapeseed Oil', '7 units', 11),
  ('Bread - Dark Rye', '4 units', 154),
  ('Salt - Celery', '2 units', 64),
  ('Broom And Broom Rack White', '2 units', 52),
  ('Wine - Magnotta - Cab Sauv', '4 units', 51),
  ('Beef - Rouladin, Sliced', '6 units', 94),
  ('Sauce - Apple, Unsweetened', '1 units', 17),
  ('Mussels - Frozen', '10 units', 120),
  ('Sugar - Cubes', '1 units', 43),
  ('Sprouts - Baby Pea Tendrils', '4 units', 48),
  ('Tomatoes - Diced, Canned', '3 units', 108),
  ('Bagelers - Cinn / Brown Sugar', '9 units', 196),
  ('Apple - Royal Gala', '2 units', 124),
  ('Wine - Riesling Alsace Ac 2001', '5 units', 52),
  ('Jack Daniels', '1 units', 159),
  ('Cheese - Cheddar, Mild', '1 units', 100),
  ('Emulsifier', '7 units', 166),
  ('Beets - Candy Cane, Organic', '7 units', 195),
  ('Fudge - Chocolate Fudge', '3 units', 136),
  ('Pasta - Orecchiette', '3 units', 19),
  ('Beer - Sleeman Fine Porter', '10 units', 187),
  ('Nacho Chips', '3 units', 126),
  ('Beer - Steamwhistle', '9 units', 40),
  ('Flour - Rye', '9 units', 20),
  ('Ostrich - Prime Cut', '5 units', 131),
  ('Pasta - Fett Alfredo, Single Serve', '1 units', 26),
  ('Beef Cheek Fresh', '5 units', 32),
  ('Wine - Casablanca Valley', '6 units', 57),
  ('Pail For Lid 1537', '7 units', 85),
  ('Lemonade - Strawberry, 591 Ml', '10 units', 150),
  ('Lettuce - Green Leaf', '6 units', 55),
  ('Cake - Bande Of Fruit', '8 units', 118),
  ('Squash - Butternut', '2 units', 109),
  ('Crab - Meat Combo', '5 units', 88),
  ('Chickhen - Chicken Phyllo', '1 units', 56),
  ('Compound - Pear', '10 units', 145),
  ('Wine - Merlot Vina Carmen', '8 units', 130),
  ('Garlic', '5 units', 105),
  ('Bread - Corn Muffaletta', '8 units', 10),
  ('Sambuca - Opal Nera', '9 units', 145),
  ('Bread Crumbs - Japanese Style', '7 units', 87),
  ('Tea - Decaf Lipton', '6 units', 109),
  ('Pepper - Gypsy Pepper', '1 units', 142),
  ('Pork - Back Ribs', '10 units', 150),
  ('Wine - Pinot Noir Stoneleigh', '4 units', 150),
  ('Muffin - Blueberry Individual', '8 units', 109),
  ('Artichoke - Fresh', '1 units', 16),
  ('Wine - Zonnebloem Pinotage', '2 units', 13),
  ('Nestea - Ice Tea, Diet', '9 units', 37),
  ('Strawberries', '5 units', 66),
  ('Beer - Moosehead', '7 units', 119),
  ('Pasta - Cappellini, Dry', '5 units', 63),
  ('Bread - Hamburger Buns', '7 units', 80),
  ('Jicama', '2 units', 43),
  ('Wanton Wrap', '8 units', 196),
  ('Juice - Happy Planet', '1 units', 148),
  ('Lettuce - California Mix', '4 units', 159),
  ('Tomatoes Tear Drop', '9 units', 146),
  ('Scampi Tail', '4 units', 165),
  ('Tortillas - Flour, 10', '8 units', 70),
  ('Beef - Bones, Marrow', '9 units', 122),
  ('Truffle Shells - White Chocolate', '7 units', 101),
  ('Beef - Ox Tail, Frozen', '4 units', 87),
  ('Pastry - French Mini Assorted', '5 units', 149),
  ('Mushroom - King Eryingii', '2 units', 108),
  ('Flour - Corn, Fine', '9 units', 142),
  ('Pomello', '8 units', 100),
  ('Snapple Lemon Tea', '9 units', 141),
  ('Coffee - French Vanilla Frothy', '8 units', 184),
  ('Oil - Sesame', '8 units', 61),
  ('Scallops - In Shell', '3 units', 175),
  ('Country Roll', '9 units', 180),
  ('Muffin Mix - Chocolate Chip', '10 units', 102),
  ('Coffee - Cafe Moreno', '7 units', 91),
  ('Doilies - 10, Paper', '7 units', 185),
  ('Peas - Pigeon, Dry', '3 units', 59),
  ('Roe - Lump Fish, Black', '10 units', 86),
  ('Chicken - Wings, Tip Off', '7 units', 148),
  ('Brocolinni - Gaylan, Chinese', '8 units', 181),
  ('Juice - Apple Cider', '9 units', 15),
  ('Peas - Frozen', '6 units', 58),
  ('Hot Choc Vending', '7 units', 16),
  ('Yogurt - Peach, 175 Gr', '4 units', 85),
  ('Peas - Pigeon, Dry', '8 units', 15),
  ('Longos - Chicken Wings', '2 units', 127),
  ('Cheese - Augre Des Champs', '3 units', 127),
  ('Oven Mitts - 15 Inch', '8 units', 182),
  ('Sugar - Monocystal / Rock', '1 units', 169),
  ('Sobe - Green Tea', '5 units', 19),
  ('Tea Leaves - Oolong', '1 units', 186),
  ('Calypso - Black Cherry Lemonade', '10 units', 160),
  ('Bananas', '7 units', 149),
  ('Crab Brie In Phyllo', '10 units', 152),
  ('The Pop Shoppe - Root Beer', '2 units', 138),
  ('Wine - Casillero Deldiablo', '6 units', 15),
  ('Cheese - Feta', '1 units', 186),
  ('Tendrils - Baby Pea, Organic', '8 units', 41),
  ('Flour - Pastry', '6 units', 151),
  ('Tea - Lemon Scented', '9 units', 68),
  ('Sambuca - Ramazzotti', '8 units', 25),
  ('Pastry - Trippleberry Muffin - Mini', '3 units', 26),
  ('Apples - Spartan', '5 units', 57),
  ('Truffle Cups - Red', '2 units', 144),
  ('Sauce - Sesame Thai Dressing', '5 units', 86),
  ('Tart - Butter Plain Squares', '8 units', 191),
  ('Chicken - Base', '5 units', 18),
  ('Figs', '1 units', 126),
  ('Sansho Powder', '2 units', 124),
  ('Cake Slab', '5 units', 186),
  ('Nut - Pecan, Pieces', '7 units', 174),
  ('Appetizer - Shrimp Puff', '2 units', 41),
  ('Huck Towels White', '2 units', 126),
  ('Cheese - Brie, Triple Creme', '10 units', 195),
  ('Salmon - Whole, 4 - 6 Pounds', '8 units', 152),
  ('Soup Bowl Clear 8oz92008', '7 units', 133),
  ('Dill - Primerba, Paste', '9 units', 170),
  ('Juice - Grape, White', '3 units', 94),
  ('Broom - Angled', '9 units', 108),
  ('Tea - Herbal Orange Spice', '10 units', 137),
  ('Versatainer Nc - 9388', '10 units', 39),
  ('White Fish - Filets', '4 units', 74),
  ('Parsley - Fresh', '6 units', 87),
  ('Buffalo - Short Rib Fresh', '5 units', 40),
  ('Wine - Sauvignon Blanc Oyster', '5 units', 39),
  ('Soup Campbells Split Pea And Ham', '5 units', 175),
  ('Mustard - Dry, Powder', '5 units', 81),
  ('Sweet Pea Sprouts', '3 units', 105),
  ('Alize Red Passion', '4 units', 127),
  ('Broccoli - Fresh', '2 units', 131),
  ('Wine - Port Late Bottled Vintage', '3 units', 66),
  ('Mangoes', '3 units', 12),
  ('Crab - Meat Combo', '3 units', 27),
  ('Dried Peach', '6 units', 161),
  ('Beans - Butter Lrg Lima', '10 units', 48),
  ('Energy Drink Red Bull', '2 units', 13),
  ('Lid - 0090 Clear', '9 units', 37),
  ('Crab - Meat', '4 units', 19),
  ('Spice - Montreal Steak Spice', '8 units', 114),
  ('Wiberg Cure', '5 units', 69),
  ('Chocolate Bar - Oh Henry', '7 units', 198),
  ('Carroway Seed', '10 units', 190),
  ('Tuna - Sushi Grade', '6 units', 162),
  ('Tea - Darjeeling, Azzura', '4 units', 128),
  ('Herb Du Provence - Primerba', '4 units', 138),
  ('Pail With Metal Handle 16l White', '8 units', 86),
  ('Asparagus - Mexican', '10 units', 70),
  ('Wine - Red Oakridge Merlot', '5 units', 12),
  ('Beans - Butter Lrg Lima', '4 units', 4),
  ('Fond - Neutral', '3 units', 13),
  ('Beer - Sleeman Fine Porter', '2 units', 134),
  ('Soup V8 Roasted Red Pepper', '10 units', 131),
  ('Flour - Whole Wheat', '7 units', 162),
  ('Island Oasis - Strawberry', '4 units', 32)
;