INSERT INTO
ingredients(ingredient_name, amount, recipe_id)
VALUES

  ('olive oil', '2 tbsp', 1),
  ('white onion', '1 small', 1),
  ('celery', '2 stalks', 1),
  ('carrot', '1 medium', 1),
  ('garlic', '3 cloves', 1),
  ('sea salt', '1/2 tsp', 1),
  ('chipotle peppers', '1-2', 1),
  ('fire-roasted tomatoes', '2 cans', 1),
  ('water', '2 cups', 1),

  ('olive oil', '2 tbsp', 2),
  ('white onion', '1 small', 2),
  ('celery', '2 stalks', 2),
  ('carrot', '1 medium', 2),
  ('garlic', '3 cloves', 2),
  ('sea salt', '1/2 tsp', 2),
  ('chipotle peppers', '1-2', 2),
  ('fire-roasted tomatoes', '2 cans', 2),
  ('water', '2 cups', 2),

  ('olive oil', '2 tbsp', 3),
  ('white onion', '1 small', 3),
  ('celery', '2 stalks', 3),
  ('carrot', '1 medium', 3),
  ('garlic', '3 cloves', 3),
  ('sea salt', '1/2 tsp', 3),
  ('chipotle peppers', '1-2', 3),
  ('fire-roasted tomatoes', '2 cans', 3),
  ('water', '2 cups', 3),

  ('olive oil', '2 tbsp', 4),
  ('white onion', '1 small', 4),
  ('celery', '2 stalks', 4),
  ('carrot', '1 medium', 4),
  ('garlic', '3 cloves', 4),
  ('sea salt', '1/2 tsp', 4),
  ('chipotle peppers', '1-2', 4),
  ('fire-roasted tomatoes', '2 cans', 4),
  ('water', '2 cups', 4),

  ('olive oil', '2 tbsp', 5),
  ('white onion', '1 small', 5),
  ('celery', '2 stalks', 5),
  ('carrot', '1 medium', 5),
  ('garlic', '3 cloves', 5),
  ('sea salt', '1/2 tsp', 5),
  ('chipotle peppers', '1-2', 5),
  ('fire-roasted tomatoes', '2 cans', 5),
  ('water', '2 cups', 5),

  ('olive oil', '2 tbsp', 6),
  ('white onion', '1 small', 6),
  ('celery', '2 stalks', 6),
  ('carrot', '1 medium', 6),
  ('garlic', '3 cloves', 6),
  ('sea salt', '1/2 tsp', 6),
  ('chipotle peppers', '1-2', 6),
  ('fire-roasted tomatoes', '2 cans', 6),
  ('water', '2 cups', 6),

  ('olive oil', '2 tbsp', 7),
  ('white onion', '1 small', 7),
  ('celery', '2 stalks', 7),
  ('carrot', '1 medium', 7),
  ('garlic', '3 cloves', 7),
  ('sea salt', '1/2 tsp', 7),
  ('chipotle peppers', '1-2', 7),
  ('fire-roasted tomatoes', '2 cans', 7),
  ('water', '2 cups', 7),

  ('olive oil', '2 tbsp', 8),
  ('white onion', '1 small', 8),
  ('celery', '2 stalks', 8),
  ('carrot', '1 medium', 8),
  ('garlic', '3 cloves', 8),
  ('sea salt', '1/2 tsp', 8),
  ('chipotle peppers', '1-2', 8),
  ('fire-roasted tomatoes', '2 cans', 8),
  ('water', '2 cups', 8),

  ('olive oil', '2 tbsp', 9),
  ('white onion', '1 small', 9),
  ('celery', '2 stalks', 9),
  ('carrot', '1 medium', 9),
  ('garlic', '3 cloves', 9),
  ('sea salt', '1/2 tsp', 9),
  ('chipotle peppers', '1-2', 9),
  ('fire-roasted tomatoes', '2 cans', 9),
  ('water', '2 cups', 9),

  ('olive oil', '2 tbsp', 10),
  ('white onion', '1 small', 10),
  ('celery', '2 stalks', 10),
  ('carrot', '1 medium', 10),
  ('garlic', '3 cloves', 10),
  ('sea salt', '1/2 tsp', 10),
  ('chipotle peppers', '1-2', 10),
  ('fire-roasted tomatoes', '2 cans', 10),
  ('water', '2 cups', 10),

  ('olive oil', '2 tbsp', 11),
  ('white onion', '1 small', 11),
  ('celery', '2 stalks', 11),
  ('carrot', '1 medium', 11),
  ('garlic', '3 cloves', 11),
  ('sea salt', '1/2 tsp', 11),
  ('chipotle peppers', '1-2', 11),
  ('fire-roasted tomatoes', '2 cans', 11),
  ('water', '2 cups', 11),

  ('olive oil', '2 tbsp', 12),
  ('white onion', '1 small', 12),
  ('celery', '2 stalks', 12),
  ('carrot', '1 medium', 12),
  ('garlic', '3 cloves', 12),
  ('sea salt', '1/2 tsp', 12),
  ('chipotle peppers', '1-2', 12),
  ('fire-roasted tomatoes', '2 cans', 12),
  ('water', '2 cups', 12),

  ('olive oil', '2 tbsp', 13),
  ('white onion', '1 small', 13),
  ('celery', '2 stalks', 13),
  ('carrot', '1 medium', 13),
  ('garlic', '3 cloves', 13),
  ('sea salt', '1/2 tsp', 13),
  ('chipotle peppers', '1-2', 13),
  ('fire-roasted tomatoes', '2 cans', 13),
  ('water', '2 cups', 13),

  ('olive oil', '2 tbsp', 14),
  ('white onion', '1 small', 14),
  ('celery', '2 stalks', 14),
  ('carrot', '1 medium', 14),
  ('garlic', '3 cloves', 14),
  ('sea salt', '1/2 tsp', 14),
  ('chipotle peppers', '1-2', 14),
  ('fire-roasted tomatoes', '2 cans', 14),
  ('water', '2 cups', 14),

  ('olive oil', '2 tbsp', 15),
  ('white onion', '1 small', 15),
  ('celery', '2 stalks', 15),
  ('carrot', '1 medium', 15),
  ('garlic', '3 cloves', 15),
  ('sea salt', '1/2 tsp', 15),
  ('chipotle peppers', '1-2', 15),
  ('fire-roasted tomatoes', '2 cans', 15),
  ('water', '2 cups', 15),

  ('olive oil', '2 tbsp', 16),
  ('white onion', '1 small', 16),
  ('celery', '2 stalks', 16),
  ('carrot', '1 medium', 16),
  ('garlic', '3 cloves', 16),
  ('sea salt', '1/2 tsp', 16),
  ('chipotle peppers', '1-2', 16),
  ('fire-roasted tomatoes', '2 cans', 16),
  ('water', '2 cups', 16),

  ('olive oil', '2 tbsp', 17),
  ('white onion', '1 small', 17),
  ('celery', '2 stalks', 17),
  ('carrot', '1 medium', 17),
  ('garlic', '3 cloves', 17),
  ('sea salt', '1/2 tsp', 17),
  ('chipotle peppers', '1-2', 17),
  ('fire-roasted tomatoes', '2 cans', 17),
  ('water', '2 cups', 17),

  ('olive oil', '2 tbsp', 18),
  ('white onion', '1 small', 18),
  ('celery', '2 stalks', 18),
  ('carrot', '1 medium', 18),
  ('garlic', '3 cloves', 18),
  ('sea salt', '1/2 tsp', 18),
  ('chipotle peppers', '1-2', 18),
  ('fire-roasted tomatoes', '2 cans', 18),
  ('water', '2 cups', 18),

  ('olive oil', '2 tbsp', 19),
  ('white onion', '1 small', 19),
  ('celery', '2 stalks', 19),
  ('carrot', '1 medium', 19),
  ('garlic', '3 cloves', 19),
  ('sea salt', '1/2 tsp', 19),
  ('chipotle peppers', '1-2', 19),
  ('fire-roasted tomatoes', '2 cans', 19),
  ('water', '2 cups', 19),

  ('olive oil', '2 tbsp', 20),
  ('white onion', '1 small', 20),
  ('celery', '2 stalks', 20),
  ('carrot', '1 medium', 20),
  ('garlic', '3 cloves', 20),
  ('sea salt', '1/2 tsp', 20),
  ('chipotle peppers', '1-2', 20),
  ('fire-roasted tomatoes', '2 cans', 20),
  ('water', '2 cups', 20),

  ('olive oil', '2 tbsp', 21),
  ('white onion', '1 small', 21),
  ('celery', '2 stalks', 21),
  ('carrot', '1 medium', 21),
  ('garlic', '3 cloves', 21),
  ('sea salt', '1/2 tsp', 21),
  ('chipotle peppers', '1-2', 21),
  ('fire-roasted tomatoes', '2 cans', 21),
  ('water', '2 cups', 21),

  ('olive oil', '2 tbsp', 22),
  ('white onion', '1 small', 22),
  ('celery', '2 stalks', 22),
  ('carrot', '1 medium', 22),
  ('garlic', '3 cloves', 22),
  ('sea salt', '1/2 tsp', 22),
  ('chipotle peppers', '1-2', 22),
  ('fire-roasted tomatoes', '2 cans', 22),
  ('water', '2 cups', 22),

  ('olive oil', '2 tbsp', 23),
  ('white onion', '1 small', 23),
  ('celery', '2 stalks', 23),
  ('carrot', '1 medium', 23),
  ('garlic', '3 cloves', 23),
  ('sea salt', '1/2 tsp', 23),
  ('peppers', '1-2', 23),
  ('tomatoes', '2 cans', 23),
  ('water', '2 cups', 23),

  ('all-purpose flour', '1.5 cups', 24),
  ('baking powder', '3.5 tsp', 24),
  ('salt', '.25 tst', 24),
  ('white sugar', '1 tbsp', 24),
  ('milk', '1.25 cups', 24),
  ('egg', '1', 24),
  ('butter', '3 tbsp', 24),

  ('chicken thighs', '7', 25),
  ('kosher salt', '1 tsp', 25),
  ('black pepper', '1/2 tsp', 25),
  ('olive oil', '2 tbsp', 25),
  ('shallots', '4', 25),
  ('galic cloves', '6', 25),
  ('cherry tomatoes', '1 pint', 25),
  ('green olives', '1/2 cup', 25),
  ('white wine', '1 cup', 25)
  ;