DROP TABLE IF EXISTS bookmarks CASCADE;

CREATE TABLE bookmarks(
  id SERIAL PRIMARY KEY NOT NULL,
  
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE
);